client:
  enabled: true
  join:
  - consul-quickstart-1651644405175.private.consul.18ee0ccc-0295-4e79-b048-c0068fe009cc.aws.hashicorp.cloud
  nodeMeta:
    terraform-module: hcp-eks-client
connectInject:
  default: true
  enabled: true
  transparentProxy:
    defaultEnabled: true
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultEnableMerging: true
controller:
  enabled: true
externalServers:
  enabled: true
  hosts:
  - consul-quickstart-1651644405175.private.consul.18ee0ccc-0295-4e79-b048-c0068fe009cc.aws.hashicorp.cloud
  httpsPort: 443
  k8sAuthMethodHost: https://2FCE1B7E88DB550DB7C9F320E9F347BE.gr7.eu-west-3.eks.amazonaws.com
  useSystemRoots: true
global:
  metrics:
    enabled: true
    enableAgentMetrics: true
    enableGatewayMetrics: true
    agentMetricsRetentionTime: "1m"
  acls:
    bootstrapToken:
      secretKey: bootstrapToken
      secretName: consul-quickstart-1651644405175-hcp
    manageSystemACLs: true
  datacenter: consul-quickstart-1651644405175
  enabled: false
  gossipEncryption:
    secretKey: gossipEncryptionKey
    secretName: consul-quickstart-1651644405175-hcp
  image: hashicorp/consul-enterprise:1.12.0-ent
  name: consul
  tls:
    caCert:
      secretKey: caCert
      secretName: consul-quickstart-1651644405175-hcp
    enableAutoEncrypt: true
    enabled: true
    httpsOnly: false
ingressGateways:
  enabled: true
  gateways:
  - name: ingress-gateway
    service:
      ports:
      - port: 80
      type: LoadBalancer
server:
  enabled: false
prometheus:
  enabled: true
