apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
data:
  otel-collector-config: |
    extensions:
        health_check:
    receivers:
        zipkin:
        k8s_cluster:
          auth_type: serviceAccount
          node_conditions_to_report: [Ready, MemoryPressure]
        otlp:
          protocols:
              grpc:
              http:
        hostmetrics:
          collection_interval: 10s
          scrapers:
            load:
            memory:
            network:
            cpu:
        prometheus:
          config:
            scrape_configs:
            - job_name: "otel-collector"
              scrape_interval: 5s
              static_configs:
                - targets: ["prometheus-server:9090"]
            - job_name: k8s
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - source_labels: [  ]
                regex: "true"
                action: keep
              metric_relabel_configs:
              - source_labels: [__name__]
                regex: "(request_duration_seconds.*|response_duration_seconds.*)"
                action: keep
              - source_labels: [__address__]
                regex: "(request_duration_seconds.*|response_duration_seconds.*)"
                action: keep
    processors:
        batch:
    exporters:
        logging:
            loglevel: debug

        # configuring otlp to public satellites
        otlp:
          endpoint: "ingest.lightstep.com:443"
          headers:
            "lightstep-access-token": '${LIGHTSTEP_ACCESS_TOKEN}'
        # awsxray:
        #   region: us-west-2
    service:
        extensions: [health_check]
        pipelines:
          traces:
            receivers: [otlp,zipkin]
            exporters: [logging, otlp]
            processors: [batch]
          metrics:
            receivers: [otlp,hostmetrics,prometheus]
            exporters: [logging, otlp]