---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: ${ingress-gw-port}
      protocol: http
      services:
        - name: api-vs
          hosts: ["*"]
